# Define a classe responsável por iniciar a comunicação com o servidor WildFly.
# Ela cria o contexto JNDI, permitindo que o cliente localize recursos remotos, como EJBs, DataSources e outros serviços.
java.naming.factory.initial=org.wildfly.naming.client.WildFlyInitialContextFactory

# Informa onde o servidor WildFly está disponível
java.naming.provider.url=http-remoting://localhost:8080